version: '3'

services:
  app:
    image: nginx:latest
    ports:
      - 10002:80
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal
    depends_on:
      - bot
      - web
  bot:
    build: bot
    environment:
      APPNAME: StaticWeb Report
      APPURL: http://web:3000/
      APPURLREGEX: ^http://web:3000/.*$
      APPFLAG: netcomp23{static_web_n0t_mean_not_vuln!}
      APPLIMIT: 2
      APPLIMITTIME: 60
    networks:
      - internal

  web:
    build: src
    networks:
      - internal

networks:
  internal:
