version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webfuscation
    ports:
      - "10004:80"
    volumes:
      - ./src:/var/www/html
