version: "3.1"
services:
    www:
        container_name: tmp-storage-app
        build: .
        ports: 
            - "10005:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        container_name: tmp-storage-db
        image: mysql:8.0
        ports: 
            - "3308:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: tmpstorage
            MYSQL_USER: tmpstorage
            MYSQL_PASSWORD: p@ssw0rd123
            MYSQL_ROOT_PASSWORD: rootp@ssw0rd123
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
volumes:
    persistent:
